apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rancher
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: 'https://github.com/aleiner/PM2026Demo.git'
              revision: main
              files:
                - path: "2-applicationset/apps/tetris/{{name}}.yaml" # BUILT-IT VARIABLE
  template:
    metadata:
      name: "tetris-{{name}}"
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/rancher-archives/rodeo.git'
          targetRevision: master
          path: charts/tetris
          helm:
            releaseName: tetris
            valueFiles:
              - $values/2-applicationset/apps/tetris/{{name}}.yaml # BUILT-IT VARIABLE
        - repoURL: 'https://github.com/aleiner/PM2026Demo.git'
          targetRevision: main
          ref: values
      destination:
        server: '{{server}}' # BUILT-IT VARIABLE
        namespace: tetris
